# Example of bipartite networks using the data generated by
# Sweet potato virome in Africa. 
# --------------------------------------------------------------------------------------
setwd("/Users/ricardoi/Dropbox (UFL)/Alcala_Briseno-Garrett/++Papa_virome/+papa/3-results/")

#----- Loading libraries -------
library(bipartite)
library(igraph)
library(dplyr)
library(plyr)
library(viridis)
library(reshape2)
library(tidyr)
library(openxlsx)
library(ggplot2)

# ----- Adding metadata --------
metadata <- read.xlsx("2_Viroma_web_180319_final.xlsx", sheet = 2)
metadata <- metadata %>% select_if(~!all(is.na(.)))
metadata

length(metadata$`Altitude.(masl)`)
hl <- metadata[which(metadata$`Altitude.(masl)` < 1000),] # hot land Hoehen index
hls<- c(table(hl$Department), Total= sum(table(hl$Department)))
cl <- metadata[which(metadata$`Altitude.(masl)` > 2000 & metadata$`Altitude.(masl)` <3400), ] # cold land Hoehen index
cls <- c(table(cl$Department), Total= sum(table(cl$Department)))
fl <- metadata[which(metadata$`Altitude.(masl)` > 3400),] # frozen land Hoehen index
fls <- c(table(fl$Department), Total= sum(table(fl$Department)))

metadata$altzones <- ifelse(metadata$`Altitude.(masl)` < 1000, "hotland",
  ifelse(metadata$`Altitude.(masl)` > 1000 & metadata$`Altitude.(masl)` <2000, "templand", 
    ifelse(metadata$`Altitude.(masl)` > 2000 & metadata$`Altitude.(masl)` <3400, "coldland",
      ifelse(metadata$`Altitude.(masl)` > 3400 & metadata$`Altitude.(masl)` <5000, "frozenland",
        ifelse(metadata$`Altitude.(masl)` > 5000, "snowline", "out of range")))))

#### Summary statistics
#   | Zona        | Departamemto  | Samples |
#   |--           |--             |--   |
#   | Hot land    | Ica           | 121 |
#   | 		        | Lima          | 110 |
#   |		          | Subtotal      | 231 |
#   | Cold land   | Cajamarca     | 147 |
#   |             | Cuzco         | 89  |
#   |             | Huanuco       | 77  |
#   |             | Junín         | 110 |
#   |	            | Subtotal	    | 423 |
#   | Frozen land | Apurímac      | 121 |
#   |             | Cusco         | 55  |
#   |             | Huancavelica  | 66  |
#   |             | Junín         | 66  |
#   |             | Puno          | 44  |
#   |	            | Subotal       | 333 |
#   |	            | Total         | 987 |
plot(sort(metadata$`Altitude.(masl)`))
abline(h =c(1000, 2000, 3400), col = "red")


#---- lat-lon

min(as.numeric(metadata$`Altitude.(masl)`))
max(as.numeric(metadata$`Altitude.(masl)`))
min(as.numeric(metadata$Longitude))
min(as.numeric(metadata$Latitude))
max(as.numeric(metadata$Latitude))
min(as.numeric(metadata$Longitude))
max(as.numeric(metadata$Longitude))

#---- District 
table(metadata$altzones)

#####----- Elevation Map: Not Working
{
#   library(raster)
# # ----- get elevation data -------------------------
# dem1<- getData("SRTM",lat = 0, lon = -90)
# dem2<- getData("SRTM",lat = -20, lon = -65)
# dem <- merge(dem1,dem2)
# 
# # ----- Country border -----------------------------
# gadm <- getData('GADM', country = "PERU", level = 0)
# # level = 0 country borders only 
# # level = 1 country and department borders
# # use st_read() if you have a shapefile
# 
# #------ Add cities of reference  -------------------
# my_points = data.frame(
#   city = c('Lima', 'Cuzco'),
#   lon =  c(-77.05,  -72),
#   lat =  c(-12.05, -13.5)
# )
# 
# #------  more libraries  -------------------
# library(sf)
# my_points = st_as_sf(my_points, coords = c("lon", "lat"), crs = 4326)
# 
# # simplified your code a little, using extent() function ############
# #create polygon to crop the elevation data file   
# Ps1 = as(extent(-80, -69, -18, 0), 'SpatialPolygons')
# crs(Ps1) = "+proj=longlat +datum=WGS84 +no_defs"
# 
# #crop the elevation data using the polygon
# # dem = crop(dem, Ps1, snap= 'out')
# 
# #lower the reolution to enable faster plotting
# # dem_lower_res <- aggregate(dem, fact=10)
# dem.p  <-  rasterToPoints(dem)
# df <-  data.frame(dem.p)
# colnames(df) = c("lon", "lat", "alt")
# 
# #plot the data
# library(ggplot2)
# ggplot(df) +
#   geom_raster(aes(lon, lat, fill = alt))+
#   scale_fill_gradientn(colours = terrain.colors(10))+
#   geom_sf(data= my_points, color= 'red')+                                         # point
#   geom_sf_label(data= my_points, aes(label= city), nudge_y = 0.1,  color= 'gray')+ # label
#   geom_tile(data=gadm, aes(long, lat))+
#   geom_tile(data= gadm, aes(long, lat), color= 'blue', fill= NA) +             # polygon
#   coord_sf(xlim = c(-83, -69), ylim = c(-18, 0))+
#   theme_bw()
}
#####
#---- Peruvian Potato Virome
# 
# papa1 <- read.xlsx("data/CIP/3_Potato_viroma_all_libaries_completed_Results_mod5.xlsx", sheet=1, startRow = 3)
# papa1[1:5,1:15]
# papa2 <- read.xlsx("data/CIP/3_Potato_viroma_all_libaries_completed_Results_mod5.xlsx", sheet=2)
# papa2[1:5,1:15]
# ncol(papa1) == ncol(papa2)
# metadata2 <- rbind(papa1, papa2) %>% 
#                 select("Library", "Place", "field", "Sample_code") 
# md <- ddply(metadata2, .(Library, Place, Sample_code), summarise, cov=mean(as.numeric(field)))
# metadata$CIP_Code %in% md$Sample_code

peruvian_potato_virome <- read.csv("peruvian_potato_virome_vsc-rpkmx_ViNAtq_Feb11.csv")[-1]
ppv = peruvian_potato_virome

ppv[1:5,1:5]
dim(ppv)
dat=ppv

# dat.x <- ddply(ppv, .(IDs, Species), summarise, RPKM=mean(RPKM_mean))
# head(dat.x)

#--------------- NOTES --------------
# Altitude and latitude change b-diversity very high 
#   and environment - paper in science about b-diversity change from tropic and northern
#   sampling size affects beta and gamma - diversity 
#   package Jost


#------
# Plot of mean contig length after removal of 50 nt
plot(dat$Length, log2(dat$RPKM),  col="black",
     xlab = "contig length", ylab = "log2(RPKM)")
abline(v=50, col="red")
title("Normalized log2(RPKM) and length\n
      (thr = all)")

#------ stacking the three altitudinals gradients
alts <- list(nhl <- dat[dat$IDs %in% hl$CIP_Code,],
             ncl <- dat[dat$IDs %in% cl$CIP_Code,],
             nfl <- dat[dat$IDs %in% fl$CIP_Code,])


#------ Summmary stats plots
dat$IDs %in% metadata$CIP_Code 
dat <- merge(dat, metadata[c(2, 1, 4, 5, 6, 7, 8, 12, 28)], by.x = "IDs", 
             by.y = "CIP_Code", incomparables = F)
# dim(dat); dim(papa)
ggplot(dat, aes(x= factor(Genus), fill= Genus))+
  theme(legend.text = element_text(size= 14), legend.title = element_text(size= 14, face="bold"))+
  # geom_point(aes(y=RPKM_mean, fill = Genus), size = 2)+
  geom_bar(position = "dodge")+
  theme(axis.text.x = element_text(angle= 90, hjust = 1))+
  theme(plot.title = element_text(hjust = 0.5, color ="1", face="bold", size=16))+
  labs(y = "No. of hits", x = "Species")+
  theme(axis.title = element_text(color="#666666", face="bold", size=16))+
  theme(axis.text.x = element_text(color="1", size=8, angle=45),
        axis.text.y = element_text(color="1", size=12 ))+
  facet_grid(~ altzones )+
  theme(strip.text.x = element_text(size = 18, colour = "1"))+
  coord_flip()


#------
zonas = c("hot land", "cold land", "frozen land")
# for (i in seq_along(alts)){
i=1
dat=alts[[i]]
data <- dat %>%
  select(IDs, Family, Genus, Species, Acronym, Length_mean, Bases_mean,
         Coverage_mean, Reads_mean, RPKM_mean, Frags_mean, FPKM_mean)
datb <- ddply(data, .(IDs, Species), summarise, cov=mean(RPKM_mean))
datc <- na.omit(datb)
datm <- tidyr::spread(datc, IDs, cov,  drop=TRUE , fill = 0)
row.names(datm) = datm$Species
datm= datm[-1]
dim(datm)

#--- Normalizationi
print(paste("normalizing", zonas[i], "dataset", sep= " "))
dat.mat <- datm/colSums(datm)*100
dat.mat = round(dat.mat, digits = 0)
#--------------------------------------------------------------------------------------
# Calculating metrics ## UNCOMMENT ALL THIS FOR BIPARTITE METRICS
# Bipartite analysis
print(paste("calculating network for", zonas[i], sep = " "))
nnl <- networklevel(dat.mat)
nsp  <- specieslevel(dat.mat)
# nnd <- nestedcontribution(dat.mat)
# plot(nnd$`lower level`)
#------------------------------------------------------------------------------------------------------------------------------
print(paste("graph for", zonas[i], sep= " "))
g = graph.incidence(dat.mat, weighted=T)
V(g)$type
V(g)$name <- c(V(g)$name[1:length(V(g)$type[V(g)$type == "FALSE"])], rep("", length(V(g)$type[V(g)$type == "TRUE"])))
V(g)$size <- c(log(nsp$`lower level`$species.strength+5)*2, log(nsp$`higher level`$degree*5))
V(g)$color <-  c(rep("orange", length(V(g)$type[V(g)$type == "FALSE"])), rep("blue", length(V(g)$type[V(g)$type == "TRUE"])))
E(g)$weight <- 2
shapes = c(rep("circle", length(V(g)$type[V(g)$type == "FALSE"])), rep("square", length(V(g)$type[V(g)$type == "TRUE"])))
pdf(paste0("Network_by_alt_", zonas[i],".pdf"), width = 20, height = 20)
plot(g,  vertex.shape=shapes, vertex.size=V(g)$size, vertex.label.cex = 1, vertex.label.color='black', vertex.frame.color="gray", #vertex.label=NA,
     vertex.frame.color="gold",   edge.curved=F,  layout=layout_with_kk(g))
dev.off()
pdf(paste0("Degree_distr_", zonas[i],".pdf"), width = 20, height = 20)
degreedistr(dat.mat)
dev.off()
}

#------- Degree distribution
degreedistr(dat.mat)
nested(dat.mat, method="wine")
#rarest species first:
visweb(sortweb(dat.mat,sort.order="inc"), type="diagonal", labsize=3,
       square="interaction", text="none", textsize = 4,circles=FALSE, frame=FALSE)


#------ Diversity indices
library(vegan)
## alpha diversity 
# data(BCI) #example data
BCI = t(dat.mat) # transposing and changing name 
H <- vegan::diversity(BCI)
simp <- vegan::diversity(BCI, "simpson")
invsimp <- vegan::diversity(BCI, "inv")
## Unbiased Simpson (Hurlbert 1971, eq. 5) with rarefy:
unbias.simp <- rarefy(BCI, 1) - 1
## Fisher alpha
alpha <- fisher.alpha(BCI)
# a1 <- fisherfit(BCI[1,])
# estimate_richness(BCI, measures="Observed")

## Plot all
pairs(cbind(H, simp, invsimp, unbias.simp, alpha), pch="+", col="blue")
## Species richness (S) and Pielou's evenness (J):
S <- specnumber(BCI) ## rowSums(BCI > 0) does the same...
J <- H/log(S)

## beta diversity defined as gamma/alpha - 1:
data(dune)
data(dune.env)
mtdt <- metadata[which(rownames(BCI) %in% metadata$CIP_Code),]
alpha <- with(mtdt, tapply(specnumber(BCI), altzones, mean))
gamma <- with(mtdt, specnumber(BCI, altzones))
gamma/alpha - 1


if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("phyloseq")
library("phyloseq")

data("GlobalPatterns")
samp_dat <- ddply(dat, .(IDs, Department, Province, 
                         District, Localidad, altzones), 
                         summarise, length=mean(Length_mean))
rownames(samp_dat) <- samp_dat$IDs
dat.x <- ddply(ppv, .(Family, Genus, Species), summarise, RPKM=mean(RPKM_mean))
dat.x$Family <- gsub( "^ ", "", dat.x$Family) 
dat.x$Genus <- gsub( "^ ", "", dat.x$Genus) 
dat.x$Species <- gsub( "^ ", "", dat.x$Species) 
rownames(dat.mat) <- gsub( "^ ", "", rownames(dat.mat))

rownames(dat.mat) %in% dat.x$Species
colnames(dat.mat) %in% samp_dat$IDs

# GP <- prune_taxa(taxa_sums(GlobalPatterns) > 0, GlobalPatterns)
GlobalPatterns@sam_data
ps <- phyloseq(otu_table(dat.mat, taxa_are_rows = T), taxa_names(dat.x), 
               sample_data(samp_dat))
ps
# ps0 <- prune_taxa(taxa_sums(ps) > 0, ps)
plot_richness(ps, measures=c("Observed", "Chao1", "Shannon","InvSimpson"))

plot_richness(ps, x="altzones", measures=c("Observed", "Chao1", "Shannon","InvSimpson"))

plot_richness(ps, x="altzones", color="Department", measures=c("Observed", "Chao1", "Shannon", "InvSimpson"))

#-----------------------------------------------------------------------------------------------------------------
# # Identify isolated nodes
# g.cond <- V(g)[igraph::degree(g) == 1]
# gi <- igraph::delete.vertices(g, g.cond) # Remove isolated nodes
# plot(gi, edge.arrow.size=1, vertex.shape=shapes, vertex.label.cex=1.3, vertex.label.color='black', vertex.frame.color="gray", 
#      vertex.frame.color="gold",   edge.curved=F,  layout=layout_with_dh(gi, maxiter=10 ,fineiter = 10, weight.edge.crossings = 1 - sqrt(edge_density(gi))))
# legend(x=-1.3, y=1.1, legend[,2], pch=21,
#        col=legend[,1], pt.bg=legend[,1], pt.cex=1, cex=.8, bty="n", ncol=1)
#------------------------------------------------------------------------------------------------------------------------------
# Bipartite projection 
# Counting the number of interactions
# Virus
is.bipartite(g)
g2 <- bipartite.projection(g)
# Vertex names and attributes
bnodes <- as.list(V(g2$proj1))
#V(g2$proj1)$color <- rcPal(14)[as.numeric(cut(as.numeric(factor(as.character(bnodes))), breaks = 14))]
# Edges names and attributes
#E(g2$proj1)$color <- rgPal(10)[as.numeric(cut(E(g2$proj1)$weight, breaks = 10))]
gp1 <- get.adjacency(g2$proj1,sparse=FALSE,attr="weight")
hist()
plot(g2$proj1,edge.width=E(g2$proj1)$weight, vertex.label=V(g2$proj1)$name)
gp2 <- get.adjacency(g2$proj2, sparse=FALSE, attr="weight")
plot(g2$proj2,edge.width=E(g2$proj2)$weight^2, vertex.label=V(g2$proj2)$name)
#--------------------------------------------------------



